django_auth/basic_app/urls.py
from django.urls import path
from . import views

app_name = 'basic_app'

urlpatterns = [
    path('home/', views.index, name='index'),
    path('login/',views.user_login, name='user_login'),
    path('register/',views.register, name='register'),
    path('logout/',views.user_logout, name='user_logout'),
]

django_auth/django_auth/urls.py
from django.contrib import admin
from django.urls import path,include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('basic_app/', include('basic_app.urls')),
    path('', views.index, name='index')
]

django_auth/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User


class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    portfolio = models.URLField(blank=True)
    picture = models.ImageField(blank= True, upload_to='profile_pics')

    def __str__(self):
        return self.user.username
    

django_auth/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','email','password')
    
class UserProfileInfoForm(forms.ModelForm):
    portfolio = forms.URLField(required=False)
    picture = forms.ImageField(required=False)
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio','picture')

django_auth/basic_app/views.py
from django.shortcuts import render
from .forms import UserForm,UserProfileInfoForm

from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login,logout,authenticate
from django.http import HttpResponseRedirect, HttpResponse


# Create your views here.
def index(request):
    return render(request, 'basic_app/index.html')


def register(request):
    registered = False
    if request.method=='POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
            
            profile.save()

            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()  
    return render(request, 'basic_app/register.html', {'user_form':user_form,
                                                      'profile_form':profile_form,
                                                      "registered":registered})


def user_login(request):
    if request.method=='POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse(index))
            else:
                return HttpResponse("User is INACTIVE!")
        else:
            print(f"someone tried with user: {username}")

    return render(request, 'basic_app/login.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse(index))

django_auth/templates/basic_app/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <title>index</title>
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
              <a class="navbar-brand" href="{% url 'index' %}">MyWepage</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'basic_app:index' %}">Home</a>
                  </li>
                  
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'basic_app:register' %}">Register</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'admin:index'%}">Admin</a>
                  </li>
                  {% if user.is_authenticated %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'basic_app:user_logout' %}">Logout</a>
                  </li>
                  {% else %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'basic_app:user_login' %}">Login</a>
                  </li>
                  {% endif %}
                </ul>
              </div>
            </div>
          </nav>
    </div>
    
   





{% block body %}
<h1>Home page</h1>
{% endblock %}
</body>
</html>

django_auth/templates/basic_app/login.html
{% extends 'basic_app/index.html' %}

{% block body %}
<h1>Login page</h1>

<form action="" method="POST">
    {% csrf_token %}
    <label for="username">UserName</label>
    <input type="text" name="username" placeholder="Enter Username">
    <label for="password">Password</label>
    <input type="password" name="password" placeholder="Enter Password">
    <input type="submit">
</form>
{% endblock %}

django_auth/templates/basic_app/register.html
{% extends 'basic_app/index.html' %}
{% load static %}

{% block body %}
<h1>Register page</h1>
{% if registered %}
    <h1>Thank you for regiostering</h1>
{% else%}


<form enctype="multipart/form-data" method="POST">
    {% csrf_token %}
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
    <input type="submit" value="Register">
</form>
{% endif %}
{% endblock %}